language: c
sudo: false

# Blacklist
#branches:
#  except:
#    - gh-pages

env:
  global:
     - PRETTYNAME="Test"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - wget https://github.com/sui77/rc-switch/archive/2.6.2.tar.gz
   - tar xf 2.6.2.tar.gz

install:
   - arduino --install-library "Adafruit ILI9341","Adafruit GFX Library"
   - sudo mv 2.6.2 /home/travis/arduino_ide/libraries/Adafruit_Test_Library

script:
   - build_main_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
